import { Recipe, Ingredient } from '../types';

export const mockIngredients: Ingredient[] = [
  { id: '1', name: 'Курица' },
  { id: '2', name: 'Рис' },
  { id: '3', name: 'Морковь' },
  { id: '4', name: 'Лук' },
  { id: '5', name: 'Чеснок' },
  { id: '6', name: 'Помидоры' },
  { id: '7', name: 'Перец болгарский' },
  { id: '8', name: 'Картофель' },
  { id: '9', name: 'Сыр' },
  { id: '10', name: 'Яйца' },
  { id: '11', name: 'Мука' },
  { id: '12', name: 'Молоко' },
  { id: '13', name: 'Говядина' },
  { id: '14', name: 'Свёкла' },
  { id: '15', name: 'Капуста' },
  { id: '16', name: 'Творог' },
  { id: '17', name: 'Сметана' },
  { id: '18', name: 'Яблоки' },
  { id: '19', name: 'Салат романо' },
  { id: '20', name: 'Клюква' },
  { id: '21', name: 'Масло сливочное' },
  { id: '22', name: 'Сахар' },
];

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Куриный суп с рисом',
    description: 'Классический куриный суп с рисом и овощами',
    category: 'Супы',
    cookingTime: 60,
    servings: 6,
    imageUrl: '/images/recipe-1.jpg',
    rating: 4.5,
    authorId: '1',
    authorName: 'Анна Кулинаркина',
    ingredients: [
      { ingredientId: '1', ingredientName: 'Курица', quantity: '500', unit: 'г' },
      { ingredientId: '2', ingredientName: 'Рис', quantity: '150', unit: 'г' },
      { ingredientId: '3', ingredientName: 'Морковь', quantity: '2', unit: 'шт' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '5', ingredientName: 'Чеснок', quantity: '2', unit: 'зубчика' },
    ],
    steps: [
      'Курицу промыть, залить водой и поставить вариться',
      'После закипания снять пену, добавить соль и варить 30 минут',
      'Добавить нарезанный лук и морковь, варить 5 минут',
      'Добавить рис, варить до готовности риса (10-15 минут)',
      'Добавить чеснок, перец, зелень, дать настояться 10 минут',
    ],
    isFavorited: false,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Овощное рагу с курицей',
    description: 'Ароматное рагу с курицей и свежими овощами',
    category: 'Ужин',
    cookingTime: 45,
    servings: 4,
    imageUrl: '/images/recipe-2.jpg',
    rating: 4.0,
    authorId: '2',
    authorName: 'Михаил Поваров',
    ingredients: [
      { ingredientId: '1', ingredientName: 'Курица', quantity: '400', unit: 'г' },
      { ingredientId: '6', ingredientName: 'Помидоры', quantity: '3', unit: 'шт' },
      { ingredientId: '7', ingredientName: 'Перец болгарский', quantity: '2', unit: 'шт' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '5', ingredientName: 'Чеснок', quantity: '3', unit: 'зубчика' },
    ],
    steps: [
      'Курицу нарезать кубиками, обжарить до золотистой корочки',
      'Добавить лук и чеснок, жарить ещё 3 минуты',
      'Добавить помидоры и перец, тушить 15 минут',
      'Посолить, поперчить, добавить зелень',
    ],
    isFavorited: false,
    createdAt: '2024-01-14T14:30:00Z',
    updatedAt: '2024-01-14T14:30:00Z',
  },
  {
    id: '3',
    title: 'Сырный суп с картофелем',
    description: 'Нежный сливочный суп с плавленым сыром',
    category: 'Супы',
    cookingTime: 40,
    servings: 4,
    imageUrl: '/images/recipe-3.jpg',
    rating: 4.8,
    authorId: '3',
    authorName: 'Елена Сладкоешкина',
    ingredients: [
      { ingredientId: '8', ingredientName: 'Картофель', quantity: '4', unit: 'шт' },
      { ingredientId: '9', ingredientName: 'Сыр', quantity: '200', unit: 'г' },
      { ingredientId: '3', ingredientName: 'Морковь', quantity: '1', unit: 'шт' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '12', ingredientName: 'Молоко', quantity: '200', unit: 'мл' },
    ],
    steps: [
      'Картофель очистить и нарезать кубиками, залить водой и варить 15 минут',
      'Обжарить лук и морковь до золотистого цвета',
      'Добавить зажарку в суп, варить 5 минут',
      'Добавить молоко и плавленый сыр, хорошо размешать',
      'Довести до кипения, снять с огня, подавать с зеленью',
    ],
    isFavorited: false,
    createdAt: '2024-01-13T18:00:00Z',
    updatedAt: '2024-01-13T18:00:00Z',
  },
  {
    id: '4',
    title: 'Борщ с говядиной',
    description: 'Насыщенный борщ со свёклой, капустой и говядиной, подаётся со сметаной',
    category: 'Супы',
    cookingTime: 90,
    servings: 6,
    imageUrl: '/images/recipe-4.jpg',
    rating: 4.9,
    authorId: '1',
    authorName: 'Анна Кулинаркина',
    ingredients: [
      { ingredientId: '13', ingredientName: 'Говядина', quantity: '600', unit: 'г' },
      { ingredientId: '14', ingredientName: 'Свёкла', quantity: '2', unit: 'шт' },
      { ingredientId: '15', ingredientName: 'Капуста', quantity: '300', unit: 'г' },
      { ingredientId: '8', ingredientName: 'Картофель', quantity: '3', unit: 'шт' },
      { ingredientId: '3', ingredientName: 'Морковь', quantity: '1', unit: 'шт' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '6', ingredientName: 'Томатная паста', quantity: '2', unit: 'ст.л.' },
    ],
    steps: [
      'Сварить бульон из говядины, около 1 часа',
      'Свёклу натереть, тушить с томатной пастой 10 минут',
      'Добавить в бульон картофель и капусту, варить 15 минут',
      'Добавить зажарку из лука, моркови и свёклы, варить ещё 10 минут',
      'Дать настояться 20 минут, подавать со сметаной и зеленью',
    ],
    isFavorited: false,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-02-01T09:00:00Z',
  },
  {
    id: '5',
    title: 'Сырники со сметаной',
    description: 'Пышные золотистые сырники из творога — идеальный завтрак',
    category: 'Завтрак',
    cookingTime: 25,
    servings: 2,
    imageUrl: '/images/recipe-5.jpg',
    rating: 4.7,
    authorId: '3',
    authorName: 'Елена Сладкоешкина',
    ingredients: [
      { ingredientId: '16', ingredientName: 'Творог', quantity: '400', unit: 'г' },
      { ingredientId: '10', ingredientName: 'Яйца', quantity: '2', unit: 'шт' },
      { ingredientId: '11', ingredientName: 'Мука', quantity: '4', unit: 'ст.л.' },
      { ingredientId: '22', ingredientName: 'Сахар', quantity: '3', unit: 'ст.л.' },
      { ingredientId: '17', ingredientName: 'Сметана', quantity: '100', unit: 'г' },
    ],
    steps: [
      'Творог размять с яйцами, сахаром и щепоткой соли',
      'Добавить муку, замесить мягкое тесто',
      'Сформировать сырники, обвалять в муке',
      'Обжарить на среднем огне по 3-4 минуты с каждой стороны',
      'Подавать горячими со сметаной',
    ],
    isFavorited: false,
    createdAt: '2024-02-03T08:30:00Z',
    updatedAt: '2024-02-03T08:30:00Z',
  },
  {
    id: '6',
    title: 'Плов с курицей',
    description: 'Рассыпчатый плов с курицей, морковью и ароматом зиры',
    category: 'Обед',
    cookingTime: 70,
    servings: 5,
    imageUrl: '/images/recipe-6.jpg',
    rating: 4.6,
    authorId: '2',
    authorName: 'Михаил Поваров',
    ingredients: [
      { ingredientId: '1', ingredientName: 'Курица', quantity: '500', unit: 'г' },
      { ingredientId: '2', ingredientName: 'Рис', quantity: '400', unit: 'г' },
      { ingredientId: '3', ingredientName: 'Морковь', quantity: '2', unit: 'шт' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '2', unit: 'шт' },
      { ingredientId: '5', ingredientName: 'Чеснок', quantity: '1', unit: 'головка' },
      { ingredientId: '', ingredientName: 'Зира', quantity: '1', unit: 'ч.л.' },
    ],
    steps: [
      'Курицу обжарить до золотистой корочки',
      'Добавить лук и морковь соломкой, жарить 10 минут',
      'Засыпать промытый рис, залить водой на два пальца выше',
      'Добавить зиру, чеснок целиком, соль, тушить под крышкой 30 минут',
      'Дать постоять 10 минут и перемешать',
    ],
    isFavorited: false,
    createdAt: '2024-02-05T12:00:00Z',
    updatedAt: '2024-02-05T12:00:00Z',
  },
  {
    id: '7',
    title: 'Котлеты с картофельным пюре',
    description: 'Сочные куриные котлеты с нежным пюре — домашняя классика',
    category: 'Обед',
    cookingTime: 50,
    servings: 4,
    imageUrl: '/images/recipe-7.jpg',
    rating: 4.4,
    authorId: '1',
    authorName: 'Анна Кулинаркина',
    ingredients: [
      { ingredientId: '', ingredientName: 'Фарш куриный', quantity: '600', unit: 'г' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '', ingredientName: 'Хлеб белый', quantity: '2', unit: 'ломтика' },
      { ingredientId: '12', ingredientName: 'Молоко', quantity: '100', unit: 'мл' },
      { ingredientId: '8', ingredientName: 'Картофель', quantity: '800', unit: 'г' },
      { ingredientId: '21', ingredientName: 'Масло сливочное', quantity: '50', unit: 'г' },
    ],
    steps: [
      'Хлеб замочить в молоке, смешать с фаршем и луком, отбить',
      'Сформировать котлеты, обжарить по 4 минуты с каждой стороны',
      'Довести до готовности под крышкой 10 минут',
      'Картофель отварить, размять с горячим молоком и маслом',
      'Подавать котлеты с пюре и свежими овощами',
    ],
    isFavorited: false,
    createdAt: '2024-02-07T13:00:00Z',
    updatedAt: '2024-02-07T13:00:00Z',
  },
  {
    id: '8',
    title: 'Бефстроганов с пюре',
    description: 'Нежные полоски говядины в сливочно-грибном соусе',
    category: 'Ужин',
    cookingTime: 55,
    servings: 4,
    imageUrl: '/images/recipe-8.jpg',
    rating: 4.6,
    authorId: '2',
    authorName: 'Михаил Поваров',
    ingredients: [
      { ingredientId: '13', ingredientName: 'Говядина', quantity: '500', unit: 'г' },
      { ingredientId: '4', ingredientName: 'Лук', quantity: '1', unit: 'шт' },
      { ingredientId: '', ingredientName: 'Шампиньоны', quantity: '200', unit: 'г' },
      { ingredientId: '17', ingredientName: 'Сметана', quantity: '200', unit: 'г' },
      { ingredientId: '11', ingredientName: 'Мука', quantity: '1', unit: 'ст.л.' },
      { ingredientId: '8', ingredientName: 'Картофель', quantity: '700', unit: 'г' },
    ],
    steps: [
      'Говядину нарезать тонкими полосками, обжарить на сильном огне',
      'Добавить лук и грибы, жарить 7 минут',
      'Посыпать мукой, добавить сметану и немного воды, тушить 15 минут',
      'Приготовить пюре из картофеля с маслом',
      'Подавать бефстроганов с пюре, посыпав петрушкой',
    ],
    isFavorited: false,
    createdAt: '2024-02-09T18:30:00Z',
    updatedAt: '2024-02-09T18:30:00Z',
  },
  {
    id: '9',
    title: 'Шарлотка с яблоками',
    description: 'Воздушный яблочный пирог по бабушкиному рецепту',
    category: 'Десерт',
    cookingTime: 60,
    servings: 8,
    imageUrl: '/images/recipe-9.jpg',
    rating: 4.8,
    authorId: '3',
    authorName: 'Елена Сладкоешкина',
    ingredients: [
      { ingredientId: '10', ingredientName: 'Яйца', quantity: '4', unit: 'шт' },
      { ingredientId: '22', ingredientName: 'Сахар', quantity: '200', unit: 'г' },
      { ingredientId: '11', ingredientName: 'Мука', quantity: '200', unit: 'г' },
      { ingredientId: '18', ingredientName: 'Яблоки', quantity: '4', unit: 'шт' },
      { ingredientId: '', ingredientName: 'Корица', quantity: '1', unit: 'ч.л.' },
    ],
    steps: [
      'Яйца взбить с сахаром до пышной светлой массы',
      'Аккуратно вмешать просеянную муку',
      'Яблоки нарезать дольками, выложить в форму, посыпать корицей',
      'Залить тестом и разровнять',
      'Выпекать 40 минут при 180 °C, проверять зубочисткой',
    ],
    isFavorited: false,
    createdAt: '2024-02-11T16:00:00Z',
    updatedAt: '2024-02-11T16:00:00Z',
  },
  {
    id: '10',
    title: 'Цезарь с курицей',
    description: 'Хрустящий салат с курицей гриль, сухариками и пармезаном',
    category: 'Салаты',
    cookingTime: 30,
    servings: 2,
    imageUrl: '/images/recipe-10.jpg',
    rating: 4.5,
    authorId: '2',
    authorName: 'Михаил Поваров',
    ingredients: [
      { ingredientId: '1', ingredientName: 'Куриное филе', quantity: '300', unit: 'г' },
      { ingredientId: '19', ingredientName: 'Салат романо', quantity: '1', unit: 'пучок' },
      { ingredientId: '', ingredientName: 'Сухарики', quantity: '100', unit: 'г' },
      { ingredientId: '9', ingredientName: 'Пармезан', quantity: '50', unit: 'г' },
      { ingredientId: '6', ingredientName: 'Помидоры черри', quantity: '10', unit: 'шт' },
      { ingredientId: '', ingredientName: 'Соус цезарь', quantity: '4', unit: 'ст.л.' },
    ],
    steps: [
      'Куриное филе обжарить на гриле и нарезать ломтиками',
      'Листья салата порвать руками, выложить на тарелку',
      'Добавить черри, сухарики и курицу',
      'Полить соусом, посыпать тёртым пармезаном',
    ],
    isFavorited: false,
    createdAt: '2024-02-13T19:00:00Z',
    updatedAt: '2024-02-13T19:00:00Z',
  },
  {
    id: '11',
    title: 'Пицца Маргарита',
    description: 'Тонкое тесто, томатный соус, моцарелла и свежий базилик',
    category: 'Выпечка',
    cookingTime: 45,
    servings: 2,
    imageUrl: '/images/recipe-11.jpg',
    rating: 4.7,
    authorId: '1',
    authorName: 'Анна Кулинаркина',
    ingredients: [
      { ingredientId: '11', ingredientName: 'Мука', quantity: '300', unit: 'г' },
      { ingredientId: '', ingredientName: 'Дрожжи', quantity: '1', unit: 'ч.л.' },
      { ingredientId: '12', ingredientName: 'Молоко', quantity: '150', unit: 'мл' },
      { ingredientId: '6', ingredientName: 'Томатный соус', quantity: '100', unit: 'г' },
      { ingredientId: '9', ingredientName: 'Моцарелла', quantity: '150', unit: 'г' },
      { ingredientId: '', ingredientName: 'Базилик', quantity: '5', unit: 'листьев' },
    ],
    steps: [
      'Замесить тесто из муки, дрожжей и тёплого молока, оставить на 30 минут',
      'Раскатать тонкую основу',
      'Смазать томатным соусом, выложить моцареллу',
      'Выпекать 12 минут при 220 °C',
      'Украсить свежим базиликом и сбрызнуть оливковым маслом',
    ],
    isFavorited: false,
    createdAt: '2024-02-15T17:30:00Z',
    updatedAt: '2024-02-15T17:30:00Z',
  },
  {
    id: '12',
    title: 'Клюквенный морс',
    description: 'Освежающий домашний морс из клюквы с лёгкой сладостью',
    category: 'Напитки',
    cookingTime: 20,
    servings: 4,
    imageUrl: '/images/recipe-12.jpg',
    rating: 4.3,
    authorId: '3',
    authorName: 'Елена Сладкоешкина',
    ingredients: [
      { ingredientId: '20', ingredientName: 'Клюква', quantity: '300', unit: 'г' },
      { ingredientId: '22', ingredientName: 'Сахар', quantity: '100', unit: 'г' },
      { ingredientId: '', ingredientName: 'Вода', quantity: '1.5', unit: 'л' },
      { ingredientId: '', ingredientName: 'Мята', quantity: '3', unit: 'веточки' },
    ],
    steps: [
      'Клюкву размять, отжать сок и убрать в холодильник',
      'Жмых залить водой, добавить сахар и мяту, довести до кипения',
      'Варить 5 минут, снять с огня',
      'Процедить, влить отжатый сок и остудить',
      'Подавать со льдом',
    ],
    isFavorited: false,
    createdAt: '2024-02-17T11:00:00Z',
    updatedAt: '2024-02-17T11:00:00Z',
  },
];
